[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
token_contract = "4VuB55bdu6fjN2jFW3cAAd4EbapnF2q7Z51v9d85pKXp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
